name: CD

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install

      - name: Build and publish to PyPI
        if: github.event_name == 'pull_request' && github.event.pull_request.base.ref == 'main'
        env:
          POETRY_PYPI_TOKEN: ${{ secrets.PYPI_API_TOKEN }}
        run: |
          poetry config pypi-token.pypi $POETRY_PYPI_TOKEN
          poetry build
          poetry publish
